# Generated by Django 3.2.7 on 2022-06-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='category',
        ),
    ]
