# Generated by Django 3.2.7 on 2022-07-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220707_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
    ]
