# Generated by Django 3.2.7 on 2022-07-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220717_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='h3tag',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
