# Generated by Django 3.2.7 on 2022-07-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_text_h3tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='h3tag',
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
