# Generated by Django 3.2.7 on 2022-07-21 15:48

import courses.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220717_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=courses.models.get_default_image, null=True, upload_to=courses.models.get_course_image_filepath),
        ),
        migrations.AddField(
            model_name='course',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
