# Generated by Django 3.2.7 on 2022-07-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220721_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='photo',
        ),
    ]
